contact1 = input("Enter your contact 1 : ")
contact2 = input("Enter your contact 2 : ")
contact3 = input("Enter your contact 3 : ")
contact4 = input("Enter your contact 4 : ")
contact5 = input("Enter your contact 5 : ")
saved_contacts = set((contact1 , contact2 , contact3 , contact4 , contact5))
contact6 = input("Enter your contact 6 : ")
adding = set((contact1 , contact2 , contact3 , contact4 , contact5))
adding.add(contact6)
removing = set((contact1 , contact2 , contact3 , contact4 , contact5 , contact6))
removing.remove(contact1)
discarding = set((contact6, contact2 , contact3 , contact4 , contact5))
discarding.discard(contact3)
discarding.pop()
print(f"================== MOBILE CONTACTS ========================= \n Original contacts: {saved_contacts} \n { } \n  After adding contacts: {adding} \n After removing contacts: {removing} \n After discarding contacts: {discarding} \n After pop contacts: {discarding} \n Remaining contacts: {discarding} \n =======================================================================")