name= input("Name: ")
print(f"Hello {name} welcome to python programming! ")
age = input("Age: ")
print(f" your age is {age} ")
food = input("Food: ")
print(f" your favourite food is {food} ")
freind_name=input("Freind name: ")
freind_age=input("Freind age: ")
city=input("City: ")
print(f" my freind name is {freind_name} and his age is {freind_age} and he lives in {city} ")
