a=int(input("Enter your first number: "))
b =int(input("Enter your second number: "))
addition = (a+b)
subtraction =(a-b)
multiplication = (a*b)
division =(a/b)
modulus = (a%b)
floor_division = (a//b)
exponential = (a**b)
print(f"Addition: {addition} \n Subtraction: {subtraction} \n Multiplication: {multiplication} \n Division: {division} \n Modulus: {modulus} \n Floor division: {floor_division} \n Exponential: {exponential}")