age = input("Age: ")
print(age)
boy_name =input("Boy name: ")
girl_name=input("Girl name: ")
boy_age =int(input("Boy age: "))
girl_age = int(input("Girl age; "))
age_diff =abs(boy_age - girl_age)
print(boy_name +" loves " + girl_name + " Age diffrence is " + str(age_diff))
print(f"{boy_name} loves {girl_name} Age difference is {age_diff}")